/**
 * MATILDA Boutique - Catálogo Oficial de Productos
 * Contiene únicamente las prendas reales provistas en la colección fotográfica.
 * Cada prenda posee su fotografía original, referencia, color visible y detalles auténticos.
 */

const PRODUCTS = [
  {
    id: 1,
    slug: 'corset-blanco-encaje-tiras',
    referencia: 'MAT-COR-001',
    nombre: 'Corset Blanco con Encaje y Tiras Finas',
    categoria: 'Corsets',
    precio: 149990,
    imagen: 'file-folio_32J0zwr.jpg',
    color: 'Blanco',
    colorHex: '#FFFFFF',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'NUEVA COLECCIÓN',
    descripcion: 'Corset estructurado de silueta entallada con costuras verticales de corsetería. Presenta delicado ribete de encaje floral en el escote recto y en el bajo en pico estilizador, con tirantes espagueti regulables.',
    detalles: [
      'Silueta estructurada con varillas de soporte',
      'Escote recto con remate de encaje bordado floral',
      'Bajo en pico tipo corsé clásico',
      'Tirantes delgados ajustables',
      'Cierre posterior ajustable'
    ]
  },
  {
    id: 2,
    slug: 'corset-rojo-escote-corazon-drapeado',
    referencia: 'MAT-COR-002',
    nombre: 'Corset Rojo Escote Corazón Copas Drapeadas',
    categoria: 'Corsets',
    precio: 159990,
    imagen: 'file-folio_5qB3qgk.jpg',
    color: 'Rojo',
    colorHex: '#D91E2A',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'FAVORITO',
    descripcion: 'Corset en tejido satén stretch en tono rojo escarlata vibrante. Copas preformadas con fruncido vertical estilizado, tirantes anchos con drapeado en hombros y bajo en punta pronunciada.',
    detalles: [
      'Copas preformadas con efecto realce y fruncido',
      'Tirantes anchos con pliegues drapeados',
      'Varillas laterales para ajuste impecable',
      'Tejido con brillo satinado sutil y elasticidad',
      'Bajo en pico estilizador'
    ]
  },
  {
    id: 3,
    slug: 'bustier-crop-top-encaje-negro',
    referencia: 'MAT-COR-003',
    nombre: 'Bustier Crop Top en Encaje Floral Negro',
    categoria: 'Corsets',
    precio: 139990,
    imagen: 'file-folio_6kEMAFn.jpg',
    color: 'Negro',
    colorHex: '#1A1A1A',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: false,
    badge: 'TENDENCIA',
    descripcion: 'Bustier crop elaborado íntegramente en fino encaje de blonda floral color negro. Copas con varilla reforzada y copas opacas que brindan excelente soporte, con acabado festoneado en escote y contorno.',
    detalles: [
      'Encaje floral delicado con acabado en ondas festoneadas',
      'Copas con aro y forro interior suave',
      'Estructura tipo bustier semitransparente en pretina',
      'Tirantes elásticos regulables',
      'Largo crop ideal para faldas y pantalones de tiro alto'
    ]
  },
  {
    id: 4,
    slug: 'blusa-satinada-rosa-mangas-volante',
    referencia: 'MAT-BLU-001',
    nombre: 'Blusa Satinada Rosa con Mangas de Doble Volante',
    categoria: 'Blusas',
    precio: 129990,
    imagen: 'file-folio_7afbgGQ.jpeg',
    color: 'Rosa Empolvado',
    colorHex: '#E2A9B2',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'ESENCIAL',
    descripcion: 'Blusa femenina confeccionada en suave satén color rosa empolvado. Diseño limpio de cuello redondo con mangas cortas estructuradas en doble capa de volantes fluidos que aportan movimiento elegante.',
    detalles: [
      'Tejido satinado sedoso de caída suave',
      'Mangas en capa doble de volantes con vuelo delicado',
      'Cuello redondo clásico cerrado',
      'Corte recto relajado muy cómodo y combinable',
      'Tono rosa empolvado distintivo de Matilda'
    ]
  },
  {
    id: 5,
    slug: 'body-seamless-cuello-redondo-moka',
    referencia: 'MAT-BOD-001',
    nombre: 'Body Seamless Cuello Redondo Tono Moka',
    categoria: 'Bodys',
    precio: 119990,
    imagen: 'file-folio_FItPMav.jpeg',
    color: 'Moka',
    colorHex: '#A08068',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: false,
    badge: 'BÁSICO DE LUJO',
    descripcion: 'Body sisa sin mangas en punto seamless compresivo color camel/moka. Diseño minimalista y sofisticado con cuello redondo cerrado y acabado ultra liso de segunda piel que moldea suavemente.',
    detalles: [
      'Tejido seamless ultra suave y adaptable',
      'Cuello cerrado redondo favorecedor',
      'Ajuste ceñido ergonómico sin marcas',
      'Cierre inferior con broches a presión',
      'Tono camel moka neutro muy versátil'
    ]
  },
  {
    id: 6,
    slug: 'top-strapless-asimetrico-botones-dorados',
    referencia: 'MAT-TOP-001',
    nombre: 'Top Strapless Asimétrico con Botones Dorados',
    categoria: 'Tops',
    precio: 149990,
    imagen: 'file-folio_FeyDfBF.jpg',
    color: 'Negro',
    colorHex: '#1A1A1A',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'EXCLUSIVO',
    descripcion: 'Top palabra de honor estructurado en crepé sastre negro. Destaca por su solapa superior asimétrica de corte geométrico y una hilera frontal de cuatro imponentes botones metálicos dorados pulidos.',
    detalles: [
      'Escote strapless con solapa asimétrica doblada',
      'Botonadura frontal ornamental con 4 maxi botones dorados',
      'Tejido crepé estructurado de alta densidad',
      'Corte entallado a la cintura',
      'Cierre invisible lateral'
    ]
  },
  {
    id: 7,
    slug: 'corset-satinado-asimetrico-maxi-lazo-rojo',
    referencia: 'MAT-COR-004',
    nombre: 'Corset Satinado Asimétrico con Maxi Lazo Rojo',
    categoria: 'Corsets',
    precio: 169990,
    imagen: 'file-folio_GudCl6i.jpg',
    color: 'Rojo',
    colorHex: '#D91E2A',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Últimas unidades',
    destacado: true,
    badge: 'EDICIÓN ESPECIAL',
    descripcion: 'Corset de alta costura en satén rojo rubí con diseño vanguardista de un solo hombro. Luce un espectacular lazo escultórico drapeado en el hombro derecho y corsetería con costuras arquitectónicas.',
    detalles: [
      'Diseño asimétrico con hombro libre y escote corazón suave',
      'Maxi lazo ornamental con caída estructurada',
      'Costuras de varilla verticales definitorias de silueta',
      'Satén de brillo lujoso y cuerpo firme',
      'Largo a la cintura ideal para coordinar con prendas claras'
    ]
  },
  {
    id: 8,
    slug: 'bustier-clasico-negro-copas-estructuradas',
    referencia: 'MAT-COR-005',
    nombre: 'Bustier Clásico Negro con Copas Balconette',
    categoria: 'Corsets',
    precio: 139990,
    imagen: 'file-folio_I2w8Bmv.jpg',
    color: 'Negro',
    colorHex: '#1A1A1A',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: false,
    badge: 'INFALTABLE',
    descripcion: 'Bustier atemporal confeccionado en satén mate y crepé negro. Copas preformadas tipo balconette con soporte de varilla, tirantes finos satinados y diseño de paneles verticales que perfilan la silueta.',
    detalles: [
      'Copas estructuradas balconette con soporte firme',
      'Canales de varillas reforzadas para contorno limpio',
      'Tirantes finos regulables',
      'Tejido stretch que se adapta cómodamente',
      'Espalda con cierre de ganchos graduables'
    ]
  },
  {
    id: 9,
    slug: 'chaleco-sastre-negro-botones-dorados',
    referencia: 'MAT-CHA-001',
    nombre: 'Chaleco Sastre Negro con Botones Dorados Joya',
    categoria: 'Chalecos',
    precio: 149990,
    imagen: 'file-folio_XDj4ZMw.jpg',
    color: 'Negro',
    colorHex: '#1A1A1A',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'TENDENCIA',
    descripcion: 'Chaleco de sastrería sin mangas en crepé negro premium. Cuello caja limpio, silueta estructurada con tres grandes botones redondos dorados metálicos y apertura en triángulo invertido en el bajo.',
    detalles: [
      'Corte de sastrería entallada con costuras princesa',
      'Tres maxi botones metálicos en tono dorado brillante',
      'Cuello redondo pulido sin solapa',
      'Abertura frontal inferior invertida en V',
      'Forro interior suave para máxima comodidad'
    ]
  },
  {
    id: 10,
    slug: 'chaleco-corto-bordado-artesanal-blanco',
    referencia: 'MAT-CHA-002',
    nombre: 'Chaleco Corto Bordado Artesanal Blanco',
    categoria: 'Chalecos',
    precio: 139990,
    imagen: 'file-folio_b3AdODp.jpg',
    color: 'Blanco',
    colorHex: '#FAF8F5',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: false,
    badge: 'BOHO CHIC',
    descripcion: 'Chaleco crop abierto de inspiración bohemia confeccionado en lino-algodón crudo. Presenta delicados bordados florales y ribetes en punto festón geométrico en contraste marrón avellana.',
    detalles: [
      'Frente abierto de silueta crop',
      'Bordados de flores y guirnaldas en hilo marrón',
      'Vivos decorativos en contorno y sisas',
      'Tejido natural liviano y transpirable',
      'Perfecto para lucir sobre tops básicos'
    ]
  },
  {
    id: 11,
    slug: 'body-halter-marfil-broche-dorado',
    referencia: 'MAT-BOD-002',
    nombre: 'Body Halter Marfil con Broche Metálico Dorado',
    categoria: 'Bodys',
    precio: 129990,
    imagen: 'file-folio_bvmain1.jpg',
    color: 'Blanco',
    colorHex: '#FAF9F6',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'NUEVA COLECCIÓN',
    descripcion: 'Body blanco marfil con escote halter cruzado al cuello. Luce un drapeado central recogido por un exclusivo herraje metálico en tono dorado orgánico que eleva cualquier conjunto.',
    detalles: [
      'Escote halter con hombros totalmente al descubierto',
      'Broche central metálico dorado de acabado escultórico',
      'Pliegues drapeados con efecto estilizador sobre el pecho',
      'Tejido elástico de alta compresión y suavidad',
      'Broches inferiores a presión para fácil postura'
    ]
  },
  {
    id: 12,
    slug: 'chaleco-lino-beige-lazos-frontales',
    referencia: 'MAT-CHA-003',
    nombre: 'Chaleco Lino Beige con Lazos Frontales y Vivo Negro',
    categoria: 'Chalecos',
    precio: 149990,
    imagen: 'file-folio_cr6SUxb.jpg',
    color: 'Beige',
    colorHex: '#E7DFD5',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'COQUETTE CHIC',
    descripcion: 'Chaleco en lino natural color arena con ribetes finos en contraste negro. Cuenta con un romántico cierre frontal mediante cuatro lazadas de cinta negra que aportan el sello coquette refinado de Matilda.',
    detalles: [
      'Cierre frontal mediante 4 lazos de cinta negra',
      'Bordes ribeteados en vivo negro a contraste',
      'Tejido de lino estructurado y fresco',
      'Costuras frontales que afinan la cintura',
      'Bajo curvo abierto muy favorecedor'
    ]
  },
  {
    id: 13,
    slug: 'camisa-crop-satinada-rosa-manga-larga',
    referencia: 'MAT-BLU-002',
    nombre: 'Camisa Crop Satinada Rosa Manga Larga',
    categoria: 'Blusas',
    precio: 159990,
    imagen: 'file-folio_hlIkq2D.jpg',
    color: 'Rosa Empolvado',
    colorHex: '#E2A9B2',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'DISTINTIVO',
    descripcion: 'Camisa crop en satén sedoso tono rosa empolvado. Posee cuello camisero clásico estructurado, hilera de botones forrados en el mismo tejido y mangas largas con puño elegante de sastrería.',
    detalles: [
      'Silueta crop moderna a la cintura',
      'Botonadura frontal con botones forrados al tono',
      'Cuello camisero estructurado',
      'Mangas largas con puños de cierre abotonado',
      'Satén premium de tacto ultrasuave y brillo editorial'
    ]
  },
  {
    id: 14,
    slug: 'chaleco-crema-botones-dorados-caracol',
    referencia: 'MAT-CHA-004',
    nombre: 'Chaleco Crema con Botones Dorados Caracol',
    categoria: 'Chalecos',
    precio: 149990,
    imagen: 'file-folio_ipVPYdy.jpg',
    color: 'Beige',
    colorHex: '#EAE5DB',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: false,
    badge: 'TENDENCIA',
    descripcion: 'Chaleco sastre en tejido crudo crema con cuello redondo cerrado y tres singulares botones metálicos dorados en relieve marino con forma de concha marina, complementado con sutil abertura inferior.',
    detalles: [
      'Botones escultóricos con relieve de concha de mar en dorado',
      'Corte sastre estructurado sin mangas',
      'Cuello caja minimalista',
      'Abertura central en el bajo que aporta holgura y movimiento',
      'Forro interno completo de gran calidad'
    ]
  },
  {
    id: 15,
    slug: 'top-asimetrico-drapeado-un-hombro-marfil',
    referencia: 'MAT-TOP-002',
    nombre: 'Top Asimétrico Drapeado Un Hombro Marfil',
    categoria: 'Tops',
    precio: 129990,
    imagen: 'file-folio_jIlLWHK.jpg',
    color: 'Crema',
    colorHex: '#F7F3E9',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: false,
    badge: 'ROMÁNTICO',
    descripcion: 'Top en punto suave color marfil crudo con diseño de escote asimétrico de un hombro. Presenta un elaborado drapeado fruncido en diagonal sobre el pecho que cae en una delicada manga corta drapeada.',
    detalles: [
      'Escote asimétrico con hombro descubierto',
      'Fruncido diagonal de acabado fluido sobre el busto',
      'Manga drapeada caída sobre el hombro',
      'Tejido elástico de tacto sedoso y caída perfecta',
      'Silueta entallada que no pierde la forma'
    ]
  },
  {
    id: 16,
    slug: 'corset-negro-encaje-blanco-transparencias',
    referencia: 'MAT-COR-006',
    nombre: 'Corset Negro con Encaje Blanco y Transparencias',
    categoria: 'Corsets',
    precio: 169990,
    imagen: 'file-folio_lfukYpc.jpg',
    color: 'Negro',
    colorHex: '#1A1A1A',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'ALTA COSTURA',
    descripcion: 'Espectacular corset estructurado que combina paneles laterales de tul negro translúcido con un frontal ricamente decorado con encaje bordado blanco en contraste, delineando y esculpiendo la figura.',
    detalles: [
      'Bordado floral de encaje blanco contrastante en copas y centro',
      'Laterales en tul negro semi-transparente respirable',
      'Estructura integral de ballenas que estilizan la silueta',
      'Tirantes finos negros ajustables',
      'Bajo en ángulo pronunciado estilizado'
    ]
  },
  {
    id: 17,
    slug: 'corset-strapless-negro-escote-esculpido-v',
    referencia: 'MAT-COR-007',
    nombre: 'Corset Strapless Negro con Escote Esculpido V',
    categoria: 'Corsets',
    precio: 149990,
    imagen: 'file-folio_qoeWQOw.jpg',
    color: 'Negro',
    colorHex: '#1A1A1A',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: false,
    badge: 'MODERNO',
    descripcion: 'Corset palabra de honor en crepé sastre negro con escote arquitectónico en V central reforzado. Silueta minimalista y moderna con paneles de contorno estructurados para un ajuste impecable.',
    detalles: [
      'Escote recto con abertura geométrica en V reforzada',
      'Sin tirantes con banda interna de sujeción siliconada',
      'Varillas verticales anatómicas que definen el talle',
      'Tejido crepé sastre elástico de acabado mate profundo',
      'Cierre invisible posterior'
    ]
  },
  {
    id: 18,
    slug: 'top-blanco-escote-recto-botones-joya',
    referencia: 'MAT-TOP-003',
    nombre: 'Top Blanco Escote Recto con Botones Joya',
    categoria: 'Tops',
    precio: 139990,
    imagen: 'file-folio_se3lE44.jpg',
    color: 'Blanco',
    colorHex: '#FFFFFF',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: false,
    badge: 'DELICADO',
    descripcion: 'Top de tirantes finos en piqué blanco inmaculado. Destaca por su escote cuadrado limpio, costuras princesa entalladas y botonadura frontal con cuatro refinados botones dorados con textura joya.',
    detalles: [
      'Escote cuadrado recto de inspiración clásica',
      'Cuatro botones metálicos dorados grabados tipo joya',
      'Tirantes espagueti que enmarcan los hombros',
      'Corte entallado con bajo en leve V invertida',
      'Tejido blanco estructurado de textura noble'
    ]
  },
  {
    id: 19,
    slug: 'corset-strapless-encaje-floral-cremallera',
    referencia: 'MAT-COR-008',
    nombre: 'Corset Strapless en Encaje Floral con Cremallera',
    categoria: 'Corsets',
    precio: 159990,
    imagen: 'file-folio_vdfaR7r.jpg',
    color: 'Blanco',
    colorHex: '#FFFFFF',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'ROMÁNTICO',
    descripcion: 'Corset palabra de honor confeccionado enteramente en fino encaje floral blanco marfil sobre forro suave. Incorpora cremallera metálica frontal visible y canales de varillas que acentúan la cintura.',
    detalles: [
      'Encaje floral delicado con motivos botánicos',
      'Cremallera metálica plateada central decorativa y funcional',
      'Escote corazón suave strapless',
      'Varillas de corsetería para ajuste ceñido perfecto',
      'Bajo en pico tipo corsé victoriano modernizado'
    ]
  },
  {
    id: 20,
    slug: 'corset-moka-satinado-varillas-contraste',
    referencia: 'MAT-COR-009',
    nombre: 'Corset Moka Satinado con Varillas en Contraste',
    categoria: 'Corsets',
    precio: 159990,
    imagen: 'file-folio_zK8WWR2.jpg',
    color: 'Moka',
    colorHex: '#9E7A68',
    tallas: ['S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'VANGUARDIA',
    descripcion: 'Corset de diseño exclusivo en satén color café moka, delineado con cintas de satén blanco en vivo contraste sobre las copas y las varillas verticales. Una pieza vanguardista y femenina.',
    detalles: [
      'Cintas de bies en satén blanco enmarcando las copas y varillas',
      'Tejido satinado moka de brillo refinado',
      'Copas balconette con aro de realce estructurado',
      'Tirantes blancos contrastantes ajustables',
      'Bajo recto a la cintura'
    ]
  },
  {
    id: 21,
    slug: 'top-halter-amarillo-espalda-abierta',
    referencia: 'CT363',
    nombre: 'Top Halter Amarillo con Espalda Abierta',
    categoria: 'Tops',
    precio: 119990,
    imagen: 'WhatsApp Image 2026-10-07 at 10.14.05 AM (1).jpeg',
    imagenes: [
      'WhatsApp Image 2026-10-07 at 10.14.05 AM (1).jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.05 AM.jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.05 AM (2).jpeg'
    ],
    color: 'Amarillo',
    colorHex: '#FCE473',
    tallas: ['XS', 'S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'NUEVA COLECCIÓN',
    fechaCarga: '2026-10-07',
    descripcion: 'Top sin mangas con cuello cerrado en tono amarillo pastel suave. Luce un diseño femenino de espalda descubierta con detalle de lazada ajustable en la cintura posterior.',
    detalles: [
      'Cuello cerrado estilo halter sin mangas',
      'Espalda descubierta con lazada posterior ajustable',
      'Silueta entallada a la cintura',
      'Tono amarillo pastel suave y luminoso',
      'Tejido estructurado de caída limpia'
    ]
  },
  {
    id: 22,
    slug: 'top-asimetrico-rosa-volantes-cascada',
    referencia: 'CT356',
    nombre: 'Top Asimétrico Rosa con Volantes en Cascada',
    categoria: 'Tops',
    precio: 149990,
    imagen: 'WhatsApp Image 2026-10-07 at 10.14.05 AM (3).jpeg',
    imagenes: [
      'WhatsApp Image 2026-10-07 at 10.14.05 AM (3).jpeg'
    ],
    color: 'Rosa Empolvado',
    colorHex: '#E2A9B2',
    tallas: ['XS', 'S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: false,
    badge: 'NUEVA COLECCIÓN',
    fechaCarga: '2026-10-07',
    descripcion: 'Top corto de corte asimétrico de un solo hombro en satén rosa empolvado. Destaca por su cascada arquitectónica de volantes con volumen sobre el hombro derecho.',
    detalles: [
      'Diseño asimétrico con hombro izquierdo libre',
      'Volantes estructurados en cascada sobre hombro derecho',
      'Corte entallado tipo crop top',
      'Tono rosa empolvado característico de Matilda',
      'Cierre lateral invisible'
    ]
  },
  {
    id: 23,
    slug: 'vestido-corto-skater-plisado',
    referencia: 'V218',
    nombre: 'Vestido Corto Skater Plisado',
    categoria: 'Vestidos',
    precio: 154990,
    imagen: 'WhatsApp Image 2026-10-07 at 10.14.06 AM (2).jpeg',
    imagenes: [
      'WhatsApp Image 2026-10-07 at 10.14.06 AM (2).jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.06 AM (1).jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.06 AM.jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.05 AM (4).jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.06 AM (3).jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.06 AM (4).jpeg'
    ],
    color: 'Azul Cielo',
    colorHex: '#A4C8E1',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'NUEVA COLECCIÓN',
    fechaCarga: '2026-10-07',
    descripcion: 'Vestido corto estilo skater con cuerpo ceñido, escote recto limpio con tirantes finos y falda de tablas plisadas que aporta movimiento dinámico. Disponible en variantes de color azul cielo, rojo, negro y blanco.',
    detalles: [
      'Escote recto limpio con tirantes finos',
      'Falda con tablas plisadas y vuelo estructurado',
      'Espalda descubierta con cierre de cremallera visible',
      'Torso ajustado con cintura definida',
      'Disponible en azul cielo, rojo escarlata, negro y blanco'
    ]
  },
  {
    id: 24,
    slug: 'vestido-blanco-encaje-tul-plumeti',
    referencia: 'MD7008',
    nombre: 'Vestido Blanco de Encaje Corsetero y Tul Plumeti',
    categoria: 'Vestidos',
    precio: 349990,
    imagen: 'WhatsApp Image 2026-10-07 at 10.14.07 AM (1).jpeg',
    imagenes: [
      'WhatsApp Image 2026-10-07 at 10.14.07 AM (1).jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.07 AM.jpeg'
    ],
    color: 'Blanco',
    colorHex: '#FAF9F6',
    tallas: ['XS', 'S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'NUEVA COLECCIÓN',
    fechaCarga: '2026-10-07',
    descripcion: 'Vestido corto romántico en tono blanco marfil con cuerpo tipo corset en encaje bordado floral y copas con soporte. Tirantes con mini volantes y falda vaporosa en tul plumeti.',
    detalles: [
      'Cuerpo corsetero con encaje floral y varillas de soporte',
      'Tirantes decorados con mini volantes delicados',
      'Falda en tul plumeti multicapa con motas bordadas',
      'Espalda abierta con cierre invisible',
      'Diseño romántico de inspiración coquette'
    ]
  },
  {
    id: 25,
    slug: 'corset-blanco-balconette-estructurado',
    referencia: 'CT361',
    nombre: 'Corset Blanco Balconette Estructurado',
    categoria: 'Corsets',
    precio: 149990,
    imagen: 'WhatsApp Image 2026-10-07 at 10.14.07 AM (3).jpeg',
    imagenes: [
      'WhatsApp Image 2026-10-07 at 10.14.07 AM (3).jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.08 AM.jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.07 AM (2).jpeg'
    ],
    color: 'Blanco',
    colorHex: '#FFFFFF',
    tallas: ['XS', 'S', 'M', 'L'],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'NUEVA COLECCIÓN',
    fechaCarga: '2026-10-07',
    descripcion: 'Corset estructurado en crepé satinado blanco con copas balconette preformadas y varillas de soporte verticales. Posee bajo en pico pronunciado, cremallera dorada en la espalda y tirantes desmontables.',
    detalles: [
      'Copas balconette preformadas con aro de realce',
      'Costuras de varillas verticales que esculpen la cintura',
      'Bajo en pico pronunciado estilo corsé clásico',
      'Cremallera metálica dorada posterior en toda la espalda',
      'Tirantes regulables y desmontables (opción strapless)'
    ]
  },
  {
    id: 26,
    slug: 'vestido-corto-halter-negro-plisado',
    referencia: 'V223',
    nombre: 'Vestido Corto Halter Negro Plisado',
    categoria: 'Vestidos',
    precio: 159990,
    imagen: 'WhatsApp Image 2026-10-07 at 10.14.08 AM (1).jpeg',
    imagenes: [
      'WhatsApp Image 2026-10-07 at 10.14.08 AM (1).jpeg'
    ],
    color: 'Negro',
    colorHex: '#1A1A1A',
    tallas: [],
    disponibilidad: 'Disponible',
    destacado: false,
    badge: 'NUEVA COLECCIÓN',
    fechaCarga: '2026-10-07',
    descripcion: 'Vestido corto en color negro con escote cuadrado alto y tirantes estilo halter. Torso entallado con costuras estilizadoras y falda corta de tablas plisadas.',
    detalles: [
      'Escote halter cuadrado con hombros al descubierto',
      'Corte ceñido al torso',
      'Falda corta plisada en tablas anchas',
      'Color negro profundo',
      'Diseño moderno y versátil'
    ]
  },
  {
    id: 27,
    slug: 'vestido-midi-negro-corsetero-foulard',
    referencia: 'V222',
    nombre: 'Vestido Midi Negro Corsetero con Foulard',
    categoria: 'Vestidos',
    precio: 219990,
    imagen: 'WhatsApp Image 2026-10-07 at 10.14.08 AM (2).jpeg',
    imagenes: [
      'WhatsApp Image 2026-10-07 at 10.14.08 AM (2).jpeg',
      'WhatsApp Image 2026-10-07 at 10.14.08 AM (3).jpeg'
    ],
    color: 'Negro',
    colorHex: '#1A1A1A',
    tallas: [],
    disponibilidad: 'Disponible',
    destacado: true,
    badge: 'NUEVA COLECCIÓN',
    fechaCarga: '2026-10-07',
    descripcion: 'Vestido de largo midi en crepé negro estructurado. Escote palabra de honor con corsé de varillas visibles, falda evasé de caída elegante y accesorio de foulard a juego anudado al cuello con caídas en la espalda.',
    detalles: [
      'Escote palabra de honor strapless estructurado',
      'Cuerpo corsetero con varillas de soporte expuestas',
      'Falda midi con pliegues suaves y movimiento fluido',
      'Foulard a juego anudado al cuello con caídas posteriores',
      'Espalda con panel anatómico para ajuste óptimo'
    ]
  }
];
